id: P004348
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:13:41.953316
source_metadata:
  id: bdr:W1KG15855
  title: དགེ་ཚུལ་ལྔ་བཅུ་པའི་ཁྲིད་ཟིན་ཚུལ་ཁྲིམས་གསལ་བའི་ཉིན་བྱེད།
  author: ''
  volumes:
    7a5c3fb9d67e43c79d9a7fa88d7a19a6:
      image_group_id: I1KG15919
      title: ''
      volume_number: 1
      total_pages: 241
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
